#!/bin/sh
set -e
SRC=/usr/share/applications/murmure.desktop
DEST=/usr/share/applications/com.al1x-ai.murmure.desktop
if [ -f "$SRC" ]; then
    mv -f "$SRC" "$DEST"
fi
update-desktop-database /usr/share/applications/ 2>/dev/null || true
exit 0
